### ISSUE TITLE
Escaping subgraph_isomorphic (graph.subisomorphic.vf2) crashes R

### ISSUE THREAD

**Issue by ugroempi** [igraph/rigraph#376]
[savedgraphs.zip](https://github.com/igraph/rigraph/files/4356170/savedgraphs.zip)
For the attached two graphs, if I use 

`graph.subisomorphic.vf2(largegraph, smallgraph) `
or 
`subgraph_isomorphic(smallgraph, largegraph, method="vf2")`

and then press Esc after a short while, R crashes. This did not happen some years ago. I have no idea when it started. Escaping a related FrF2 call is mentioned as a demo possibility in my FrF2 documentation, and someone recently alerted me to the problem.

Best, Ulrike

**Comment by szhorvat** [comment]
The `smallgraph` object in the file appears to be `NULL`. Can you correct it?

What is your R/igraph version and what OS are you using?

**Comment by ugroempi** [comment]
Sorry, should be corrected now. I am on Windows 10, igraph is 1.2.4.2, R version is 3.6.0.

**Comment by szhorvat** [comment]
I can reproduce the issue on macOS. It may be a problem in the C core. I will investigate.

**Comment by szhorvat** [comment]
I was unable to reproduce the problem with the Mathematica interface. Of course, no crash doesn't mean that there is no problem. 

When running R in a terminal, this is what it looks like:

```
> subgraph_isomorphic(smallgraph, largegraph, method="vf2")
^C
R(91145,0x110a265c0) malloc: *** error for object 0x7fa7358d5b68: pointer being freed was not allocated
R(91145,0x110a265c0) malloc: *** set a breakpoint in malloc_error_break to debug
fish: “R” terminated by signal SIGABRT (Abort)
```

**Comment by szhorvat** [comment]
@ugroempi You are probably aware of this already, but as a workaround you can use the 'lad' method, which is generally faster anyway. Thanks for reporting this issue!

**Comment by ugroempi** [comment]
Thanks for the lad pointer. Indeed, I am aware of lad. (vf2 with vertices sorted by degree also works fast and does not need to be escaped).

**Comment by szhorvat** [comment]
> does not need to be _escaped_

_Interrupted_ would be the more commonplace term (for other readers who may be confused).

> vf2 with vertices sorted by degree also works fast

Does this strategy work for speeding up VF2 in general? If yes, do you have more information about it?

**Comment by vtraag** [comment]
> @vtraag Can you test this with an R/igraph built with the latest C core?

This problem does not appear when using with the latest C core, as integrated in this [PR](https://github.com/igraph/rigraph/pull/372). Just to be sure: pressing `Esc` does nothing for me, I press `Ctrl-C` to interrupt the process. I assume that is what was meant.

**Comment by ugroempi** [comment]
> 
> 
> > @vtraag Can you test this with an R/igraph built with the latest C core?
> 
> This problem does not appear when using with the latest C core, as integrated in this [PR](https://github.com/igraph/rigraph/pull/372). Just to be sure: pressing `Esc` does nothing for me, I press `Ctrl-C` to interrupt the process. I assume that is what was meant.

I did indeed press <Esc>, and it used to interrupt calculations, while it now crashes them.

**Comment by ugroempi** [comment]
> 
> 
> > does not need to be _escaped_
> 
> _Interrupted_ would be the more commonplace term (for other readers who may be confused).
> 
> > vf2 with vertices sorted by degree also works fast
> 
> Does this strategy work for speeding up VF2 in general? If yes, do you have more information about it?

Pre-sorting vertices was a suggestion by Gabor. It sometimes helps and sometimes doesn't. Everything heavily depends on the nature of the graphs to be compared. I have not made any systematic investigations. For the two graphs `smallgraph` and `largegraph`, LAD and VF2 with both variants of sorting vertices (high to low degree or low to high degree) yield a solution relatively fast, whereas VF2 without pre-sorting vertices is very very slow.

**Comment by szhorvat** [comment]
> This problem does not appear when using with the latest C core

I'd say this can be closed then (I don't have the permission to do it)? While segfaults can be hard to reproduce, a bad `free()` should crash consistently. It must have gotten fixed in the C core at some point.

**Comment by gaborcsardi** [comment]
No, I am fairly sure that this is because of the errors in the R error and/or interrupt handler, and yeah, it is expected to be non-deterministic.

**Comment by vtraag** [comment]
> > This problem does not appear when using with the latest C core
> 
> I'd say this can be closed then (I don't have the permission to do it)? While segfaults can be hard to reproduce, a bad `free()` should crash consistently. It must have gotten fixed in the C core at some point.

The problem also does not appear with the current `dev` branch it seems. It does occur (but intermittently) with the latest released version (1.2.5). 

By the way: I now actually see that the [igraph.org](https://igraph.org/r/) website does not yet contain the most recent documentation for version 1.2.5, nor have any post-1.0.0 releases of the R interface been announced on the website. It also does not yet point to the new [support forum](https://igraph.discourse.group/) in order to get help.

**Comment by ntamas** [comment]
If you are fast, you can grab a recent test build from winbuilder: [R 4.1.1](https://win-builder.r-project.org/I0t2F8ofw8WV/) or [R 4.0.5](https://win-builder.r-project.org/kfu7Sx6k7fa2).

**Comment by ugroempi** [comment]
Thanks, just installed the zip file for 4.0.5. And alas: I still get the crash on Esc for both commands. Ctrl-C doesn't do anything, but Esc crashes R. The crash happens both in RStudio and from the basic R GUI. The computer I use now is not the same one that I used when reporting this for the first time, so any relevant settings seem to persist (I have no idea whether there are relevant keyboard settings or anything else of relevance on my Windows 10 machine).

Best, Ulrike

**Comment by ntamas** [comment]
#516 most likely solves this issue.

**Comment by szhorvat** [comment]
@ugroempi Can you please test this again? Windows binaries are now available for 1.3.0, so you should be able to install normally. If it works, please go ahead and close the issue.

**Comment by ntamas** [comment]
Windows binaries are available for r-devel only at the moment, you need to wait a bit and [check here](https://cran.r-project.org/web/packages/igraph/index.html) whether r-release has been updated for Windows or not.

**Comment by ntamas** [comment]
Windows binaries for 1.3.0 are out. I've tested this with RGui on Windows; pressing Ctrl-C does nothing, but pressing the Stop button in the header now stops the calculation correctly, without crashes.

@ugroempi If you have some time, please test it yourself and let us know whether the  issue can be closed.

**Comment by szhorvat** [comment]
Ctrl-C is expected to work in the terminal version (`Rterm.exe`)

**Comment by ntamas** [comment]
No, it's all versions now; see [here](https://cran.r-project.org/web/packages/igraph/index.html). The page you linked to only lists whether CRAN has checked the published version for problems.

**Comment by szhorvat** [comment]
@ugroempi Did you get the chance to test this?

**Comment by ugroempi** [comment]
@szhorvat Thanks for the reminder. 

I now checked on my Windows 10 machine from within RStudio, and the problem has gone, <Esc> works and <ctrl>-C does not do anything.
Thus I close the issue.
