### ISSUE TITLE
R is killed in Windows when contracting a graph and combining vertices

### ISSUE THREAD

**Issue by clpippel** [igraph/rigraph#398]
Here is a reproducible example:
```
library(igraph)
g  <- graph_from_literal( 1-+2, 1-+5, 2+-+3,4+-+5,2-+6,4-+6)
SCC <- clusters(g, mode=c("strong"))
g2 <- contract(g,SCC$membership, vertex.attr.comb=list(category="first", name=function(z)x[1]))
plot(g2)
```
This results into:
  "Error in function(z) : object z not found", which is correct.
  Then after a few seconds R terminates instead of continuing.

sessionInfo()
```
R version 3.6.1 (2019-07-05)
 Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)
attached base packages:
 [1] stats     graphics  grDevices utils     datasets  methods   base     
 
 other attached packages:
[1] igraph_1.2.4.1
 
 loaded via a namespace (and not attached):
[1] compiler_3.6.1  magrittr_1.5    pkgconfig_2.0.3
```

**Comment by ntamas** [comment]
FWIW, same in macOS although the crash is different:

```
> library(igraph)
> g  <- graph_from_literal( 1-+2, 1-+5, 2+-+3,4+-+5,2-+6,4-+6)
> SCC <- clusters(g, mode=c("strong"))
> g2 <- contract(g,SCC$membership, vertex.attr.comb=list(category="first", name=function(z)x[1]))
Error in (function (z)  : object 'x' not found
R(12538,0x10be5ddc0) malloc: *** error for object 0x7fe8ce43ad98: pointer being freed was not allocated
R(12538,0x10be5ddc0) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      R
```

I tried to dig into the source code of the R interface a bit (although I'm not too familiar with R) but could not find anything that looks fishy with my limited understanding of the R internals. I'm fairly sure that the error lies somewhere in `R_igraph_ac_func()` that is responsible for going back to R from C when the attribute conversion function has to be executed, but that's all I could figure out. I think we need to wait for @gaborcsardi to chime in.

**Comment by gaborcsardi** [comment]
This is obviously a bug, in the error handling code, the destructor points to the stack, which have been removed already. 

It does work if you actually fix the error in the code:

```r
library(igraph)
g  <- graph_from_literal(1 -+ 2, 1 -+ 5, 2 +-+ 3, 4 +-+ 5, 2 -+ 6,4 -+ 6)
SCC <- clusters(g, mode = c("strong"))
g2 <- contract(g, SCC$membership, vertex.attr.comb = list(category = "first", name = function(z) z[1]))
plot(g2)
```

**Comment by clpippel** [comment]
The objective was to combine two names, to keep the graph tidy and readable. So after some trial and error I arrived at:
`name=function(x) paste(x[seq_len(min(2, length(x)))], collapse="=")`

During the trial and error I run into the crash. My point is: if the bug is somewhere in a crucial function, then it may lead to errors not so easy to spot. I am new on github / R. I wonder how bugs are addressed/repaired in the open source environment. Any bug not understood is a thread to the integrity of the system. That is the reason I mention them here. Correcting the error or finding a workaround is not my greatest problem.

**Comment by szhorvat** [comment]
@ntamas I believe this got resolved by your recent fix, but I'll leave it to you to close.

**Comment by ntamas** [comment]
Yes, it seems like the combination of https://github.com/igraph/rigraph/commit/70c3547689880c1910cb8f994c394e2b36a21acb and https://github.com/igraph/rigraph/commit/c5979e654188ca33b60d68d5c0c89b25632238f5 fixed the issue. This is what I get now:

```
>  g  <- graph_from_literal( 1-+2, 1-+5, 2+-+3,4+-+5,2-+6,4-+6)
> SCC <- clusters(g, mode=c("strong"))
> g2 <- contract(g,SCC$membership, vertex.attr.comb=list(category="first", name=function(z)x[1]))
Error in (function (z)  : object 'x' not found
Error in contract(g, SCC$membership, vertex.attr.comb = list(category = "first",  :
  VECTOR_ELT() can only be applied to a 'list', not a 'builtin'
```

It's still not perfect; the second error message makes no sense to me in this context so I leave it open for a while until I investigate this.

**Comment by ntamas** [comment]
Okay, I've tested this now and it seems like the second error message is gone, so I consider this fixed.
